### ISSUE TITLE
Support passing a link to STIX JSON as a parameter

### ISSUE THREAD

**Issue by johnwunder** [oasis-open/cti-stix-visualization#17]
The visualizer should support passing a parameter (likely via hash given how it's hosted) to raw JSON that it would visualize. This would let us link to specific visualizations.

**Comment by SecurityDozo** [comment]
@johnwunder Looks like I can't assign myself to this issue. Please do that for me :) Once done, I'
ll have links on the https://github.com/oasis-open/cti-documentation page

**Comment by gtback** [comment]
@Bojak4616 you should be able to make a PR to this repo. I'm a little surprised I can't assign the issue to you, though. If you need to be added as a maintainer of this repo ( @oasis-open/cti-stix-visualization-write ), @robincover can do that.

**Comment by SecurityDozo** [comment]
I think only 'contributors' have that permission. We are mere members haha

**Comment by robincover** [comment]
Fixed per request from leads
