### ISSUE TITLE
Alert user if URL provided is somehow invalid

### ISSUE THREAD

**Issue by Bojak4616** [oasis-open/cti-stix-visualization#19]
There is currently no feedback to the user, without them checking the console log, if they fetch a url that fails.

Possible issues include:
* 404 or 500 errors
* Invalid domain
* Cross Origin error
* Better error message if file is not JSON

Simple alert message with what error occurred should suffice.

**Comment by SecurityDozo** [comment]
Fixed in PR https://github.com/oasis-open/cti-stix-visualization/pull/21
