### ISSUE TITLE
Incorrectly representing Granular Markings

### ISSUE THREAD

**Issue by MrPenguin1** [oasis-open/cti-stix-visualization#26]
When the visualizer processes a block of JSON which contains granular markings, it fails to properly render their relationships. In the example at the following URI, two of the granular markings become orphaned nodes on the graph.
https://oasis-open.github.io/cti-documentation/examples/using-granular-markings

**Comment by gtback** [comment]
Thanks, @MrPenguin1 . We'll try to look into this soon. It's hard to visually represent granular markings which may apply only to a subset of object fields. It may be best to hide them entirely and just show them in the table instead.
