### ISSUE TITLE
STIX 2.1 Updates

### ISSUE THREAD

**Issue by ikiril01** [oasis-open/cti-stix-visualization#30]
We should add the ability to render STIX 2.1 content such as Location, Opinion, Note, etc. (including their new icons).

**Comment by clenk** [comment]
The [icons repo](https://github.com/freetaxii/stix2-graphics) already has icons for Location and Note. The only SDO missing an icon is Opinion (as far as 2.1 CSD01 is concerned).

See https://github.com/freetaxii/stix2-graphics/issues/5.

**Comment by clenk** [comment]
Fixed by 16b0ffbc501226f47c78a54946e60db40d40ed95.
