### ISSUE TITLE
The icons are not displayed correctly

### ISSUE THREAD

**Issue by diedel** [oasis-open/cti-stix-visualization#37]
Apparently it crashed after the last commit. The STIX 2 icons (attack-pattern, malware, etc.) are shown as ?.

Try to copy/paste any JSON bundle.

In the other hand if you try the ?url=test.json link it can be fixed by pressing F5.

**Comment by clenk** [comment]
Hi @diedel, thanks for the comment. This has been fixed in 7250212.
