### ISSUE TITLE
Front End Issue on Jupyter Notebook

### ISSUE THREAD

**Issue by adamtimmins** [oasis-open/cti-stix-visualization#45]
Hi,

I followed the readme and encountered no errors until I tried to run the example provided. 
This error appears in the console anytime I try display the data. 
![image](https://user-images.githubusercontent.com/18688989/100911766-8a65dd80-34c7-11eb-9f3f-48fce18a5dea.png)

I installed the latest version of Jupyter and this same error occured. 

Any help appreciated.

**Comment by chisholm** [comment]
That readme has a mistake, which I suspect lay hidden until someone tried it with python 3.  Try:

```python
import requests
import stix2viz

data = requests.get("https://raw.githubusercontent.com/oasis-open/cti-stix-visualization/master/test.json").text
stix2viz.display(data)
```

The difference is in `.text` at the end of the `requests.get()` line.  `.content` returns the HTTP response content as binary.  In python2, this is a `str`, which is a binary type but tended to be interchangable with the text type, `unicode`.  In python3, there is a more significant difference between binary and text data.  If you pass a binary blob where text is expected, you're more likely to get errors.

**Comment by adamtimmins** [comment]
Still getting a frontend error every time a run this.  

![image](https://user-images.githubusercontent.com/18688989/102326983-fc84fa80-3f7c-11eb-9fb7-45ab7bff114e.png)

Am I missing certain packages to run this?

![image](https://user-images.githubusercontent.com/18688989/102328378-e8da9380-3f7e-11eb-8154-f677242e8069.png)

**EDIT** I tried it out using the Classic Notebook option in Jupyter and it's working.
