### ISSUE TITLE
How to update for v2.1???

### ISSUE THREAD

**Issue by brettforbes** [oasis-open/cti-stix-visualization#58]
Hi,

This is great.

How to update for v2.1

Can you advise on the rough overview of tasks please?

thanks

**Comment by ejratl** [comment]
@brettforbes The STIX visualizer already works on STIX 2.1 content.

**Comment by brettforbes** [comment]
rhanks, sorry it says 2.0 in the 3rd paragraph of the readme

**Comment by ejratl** [comment]
Oh, I see. I will update the documentation, thanks for letting me know!
